services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536m
        reservations:
          cpus: "0.5"
          memory: 512m

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms256m -Xmx1g -XX:MaxDirectMemorySize=512m
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1536m
        reservations:
          cpus: "0.5"
          memory: 512m

volumes:
  jenkins_data:
  nexus_data:
